# Site settings
title: "Hao Yu (Cody)"
email: TBA
description: "Applied Scientist at AWS AI, Amazon"
baseurl: ""
url: "http://comaniac.github.io"
title_description: ""
title_image: "http://graph.facebook.com/10153000246726270/picture"
google_analytics: ""
disqus_account:
github_repository: https://github.com/comaniac/comaniac.github.io
addthis_id:
post_limit: 0

# Social usernames/URLs
github_username: comaniac
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/cody-hao-yu/
google_plus_link: 
stackoverflow_link:
xing_link:
facebook_link: https://www.facebook.com/comaniac

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
