# Site settings
title: "Hao Yu (Cody)"
email: TBA
description: > # this means to ignore newlines until "baseurl:"
  I joined Tensor Virtual Machine (tvm) in Amazon Web Service as an applied scientist since August 2019.
  Prior to that, I got my Ph.D. degree from UCLA Computer Science in 2019. My research interest is 
  1) raising an abstraction level for customized computing, and 
  2) comprehensive design space exploration with several iterative approaches such as 
  hyper-heuristic and policy gradient methods.
baseurl: ""
url: "http://comaniac.github.io"
title_description: "Applied Scientist at AWS AI, Amazon"
title_image: "https://i.imgur.com/sDf6XP3.jpg"
google_analytics: UA-144617686-1
disqus_account: hao-yu-cody
github_repository: https://github.com/comaniac/comaniac.github.io
addthis_id:
post_limit: 3

# Social usernames/URLs
github_username: comaniac
instagram_username: 
reddit_username: 
twitter_username: CodyHaoYu
linkedin_link: https://www.linkedin.com/in/cody-hao-yu/
stackoverflow_link:
xing_link:
facebook_link: https://www.facebook.com/comaniac
google_scholar_link: https://scholar.google.com/citations?user=jWRhmqoAAAAJ

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fab fa-github\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
