# Site settings
title: "(Cody) Hao Yu"
email: TBA
description: > # this means to ignore newlines until "baseurl:"
  In my career life, I keep seeking for a sweet spot between challenging but exciting research
  and practical, impactful production. My journey starts by pursing Ph.D. at UCLA.
  My research interest incluldes 1) raising an abstraction level for customized computing,
  and 2) comprehensive design space exploration with several iterative approaches such as 
  hyper-heuristic and policy gradient methods.

  After graduation, I joined Amazon Web Services to continue my research life. At AWS AI,
  I was doing research related to Deep Learning Compiler (Apache TVM) and Machine Learning
  System. Then I switched gear by joining BosonAI to make product-oriented LLM systems.
  Now I am with Anyscale to continue making LLM system practical for production use cases.
baseurl: ""
url: "http://comaniac.github.io"
google_analytics: UA-144617686-1
disqus_account: hao-yu-cody
github_repository: https://github.com/comaniac/comaniac.github.io
addthis_id:
post_limit: 3

# Social usernames/URLs
github_username: comaniac
instagram_username: 
reddit_username: 
twitter_username: CodyHaoYu
linkedin_id: cody-hao-yu
stackoverflow_link:
xing_link:
facebook_link: https://www.facebook.com/comaniac
google_scholar_link: https://scholar.google.com/citations?user=jWRhmqoAAAAJ

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fab fa-github\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
